project:
  name: lab1-central-ips-ids

tests:
  lab1-test:
    template: templates/master-network-account.yml
    regions:
      - "us-east-1"
    parameters:
      pJoeyIp: "100.100.100.100"
      pJoeyHomePsk: "totallybogus"
      pSsmInstanceProfile: $[taskcat_random-string]
      MgmtAllowedIP: 52.95.4.12/32
      KeyName: mna